adminUser: admin
adminPassword: "admin"

service:
  type: NodePort
  nodePort: 30300

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-path

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.scloud-observability.svc.cluster.local:3100/
        isDefault: false
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir.scloud-observability.svc:9009/prometheus
        isDefault: true

# Option: expose via Traefik Ingress
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.scloud.internal