tempo:
  auth_enabled: false

  metricsGenerator:
    enabled: true

tempoConfig:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  overrides:
    metrics_generator_processors:
      - local-blocks

persistence:
  enabled: true
  size: 2Gi
  storageClassName: local-path

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

service:
  type: ClusterIP